name: Tests
"on":
    pull_request: {}
    push:
        branches:
            - main
jobs:
    create-package:
        name: Create Package Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/setup-go@v3
              with:
                go-version: "1.18"
            - name: Install create-package
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                go install -ldflags="-s -w" github.com/paketo-buildpacks/libpak/cmd/create-package@latest
            - name: Install pack
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing pack ${PACK_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --location \
                  --show-error \
                  --silent \
                  "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
                | tar -C "${HOME}"/bin -xz pack
              env:
                PACK_VERSION: 0.27.0
            - name: Enable pack Experimental
              if: ${{ false }}
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Enabling pack experimental features"

                mkdir -p "${HOME}"/.pack
                echo "experimental = true" >> "${HOME}"/.pack/config.toml
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-go-${{ hashFiles('**/buildpack.toml', '**/package.toml') }}
                path: |-
                    ${{ env.HOME }}/.pack
                    ${{ env.HOME }}/carton-cache
                restore-keys: ${{ runner.os }}-go-
            - name: Compute Version
              id: version
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                if [ -z "${GITHUB_REF+set}" ]; then
                  echo "GITHUB_REF set to [${GITHUB_REF-<unset>}], but should never be empty or unset"
                  exit 255
                fi

                if [[ ${GITHUB_REF} =~ refs/tags/v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
                  VERSION=${BASH_REMATCH[1]}

                  MAJOR_VERSION="$(echo "${VERSION}" | awk -F '.' '{print $1 }')"
                  MINOR_VERSION="$(echo "${VERSION}" | awk -F '.' '{print $1 "." $2 }')"

                  echo "::set-output name=version-major::${MAJOR_VERSION}"
                  echo "::set-output name=version-minor::${MINOR_VERSION}"
                elif [[ ${GITHUB_REF} =~ refs/heads/(.+) ]]; then
                  VERSION=${BASH_REMATCH[1]}
                else
                  VERSION=$(git rev-parse --short HEAD)
                fi

                echo "::set-output name=version::${VERSION}"
                echo "Selected ${VERSION} from
                  * ref: ${GITHUB_REF}
                  * sha: ${GITHUB_SHA}
                "
            - name: Create Package
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                if [[ "${INCLUDE_DEPENDENCIES}" == "true" ]]; then
                  create-package \
                    --source ${SOURCE_PATH:-.} \
                    --cache-location "${HOME}"/carton-cache \
                    --destination "${HOME}"/buildpack \
                    --include-dependencies \
                    --version "${VERSION}"
                else
                  create-package \
                    --source ${SOURCE_PATH:-.} \
                    --destination "${HOME}"/buildpack \
                    --version "${VERSION}"
                fi

                PACKAGE_FILE=${SOURCE_PATH:-.}/package.toml
                [[ -e ${PACKAGE_FILE} ]] && cp ${PACKAGE_FILE} "${HOME}"/package.toml
                printf '[buildpack]\nuri = "%s"\n\n[platform]\nos = "%s"\n' "${HOME}"/buildpack "${OS}" >> "${HOME}"/package.toml
              env:
                INCLUDE_DEPENDENCIES: "true"
                OS: linux
                VERSION: ${{ steps.version.outputs.version }}
            - name: Package Buildpack
              run: |-
                #!/usr/bin/env bash

                set -euo pipefail


                PACKAGE_LIST=($PACKAGES)
                # Extract first repo (Docker Hub) as the main to package & register
                PACKAGE=${PACKAGE_LIST[0]}

                if [[ "${PUBLISH:-x}" == "true" ]]; then
                  pack buildpack package \
                    "${PACKAGE}:${VERSION}" \
                    --config "${HOME}"/package.toml \
                    --publish

                  if [[ -n ${VERSION_MINOR:-} && -n ${VERSION_MAJOR:-} ]]; then
                    crane tag "${PACKAGE}:${VERSION}" "${VERSION_MINOR}"
                    crane tag "${PACKAGE}:${VERSION}" "${VERSION_MAJOR}"
                  fi
                  crane tag "${PACKAGE}:${VERSION}" latest
                  echo "::set-output name=digest::$(crane digest "${PACKAGE}:${VERSION}")"

                  # copy to other repositories specified
                  for P in "${PACKAGE_LIST[@]}"
                    do
                      if [ "$P" != "$PACKAGE" ]; then
                        crane copy "${PACKAGE}:${VERSION}" "${P}:${VERSION}"
                        if [[ -n ${VERSION_MINOR:-} && -n ${VERSION_MAJOR:-} ]]; then
                           crane tag "${P}:${VERSION}" "${VERSION_MINOR}"
                           crane tag "${P}:${VERSION}" "${VERSION_MAJOR}"
                        fi
                        crane tag "${P}:${VERSION}" latest
                      fi
                    done

                else
                  pack buildpack package \
                    "${PACKAGE}:${VERSION}" \
                    --config "${HOME}"/package.toml \
                    --format "${FORMAT}"
                fi
              env:
                FORMAT: image
                PACKAGES: test
                VERSION: ${{ steps.version.outputs.version }}
            - name: Run Integration Tests
              run: "BP_UNDER_TEST=${PACKAGE}:${VERSION} make integration"
              env:
                PACKAGE: test
                VERSION: ${{ steps.version.outputs.version }}
